# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe SubmittersController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Submitter. As you add validations to Submitter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { first_name: 'Test', last_name: 'Case', college: 1, department: 'Application Development', mailing_address: '2911 Woodside', phone_number: '111-111-1111', email_address: 'test@mail.uc.edu' }
  end

  let(:invalid_attributes) do
    { first_name: '', last_name: '', college: 1, department: 'Application Development', mailing_address: '', phone_number: '', email_address: 'bad_email' }
  end

  let(:new_attributes) do
    { first_name: 'New', last_name: 'Submitter', college: 2, department: 'Not Important', mailing_address: 'Home Address', phone_number: '513-111-1111', email_address: 'test@gmail.com' }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubmittersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #show' do
    it 'returns a success response' do
      submitter = Submitter.create! valid_attributes
      get :show, params: { id: submitter.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      submitter = Submitter.create! valid_attributes
      get :edit, params: { id: submitter.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Submitter' do
        expect do
          post :create, params: { submitter: valid_attributes }, session: valid_session
        end.to change(Submitter, :count).by(1)
      end

      it 'redirects to the publications show page' do
        post :create, params: { submitter: valid_attributes }, session: valid_session
        expect(response).to redirect_to(other_publications_path)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { submitter: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      it 'updates the requested submitter' do
        submitter = Submitter.create! valid_attributes
        put :update, params: { id: submitter.to_param, submitter: new_attributes }, session: valid_session
        submitter.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the submitter' do
        submitter = Submitter.create! valid_attributes
        put :update, params: { id: submitter.to_param, submitter: valid_attributes }, session: valid_session
        expect(response).to redirect_to(publications_path)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'edit' template)" do
        submitter = Submitter.create! valid_attributes
        put :update, params: { id: submitter.to_param, submitter: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end
end
